django_lesson/urls.py
#
from django.conf.urls import url
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import path, include
from django.contrib import admin
from django_lesson import settings


def home(request):
    if request.method == 'GET':
        msg = {'message': 'Hello there'}
        return render(request, 'index.html', msg)
    # loginしていなかったら、login → (/auth/login)へリダイレクトする


urlpatterns = [
                  path('home/', home, name="home"),
                  path('admin/', admin.site.urls),
                  path('todo/', include('todo.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('plot/', include('plot.urls')),
                  path('sns/', include('sns.urls')),
                  path('sns_comment/', include('sns_comment.urls')),
                  path('auth/', include('allauth.urls')),
                  path('', include('accounts.urls')),
                  url(r'^rest-auth/', include('rest_auth.urls')),
                  url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sns/urls.py
from django.urls import path

from sns import views

app_name = 'sns'

urlpatterns = [
    path('', views.SnsIndexView.as_view(), name='sns_index'),
    path('detail/<int:pk>', views.SnsDetailView.as_view(), name='sns_detail'),
    path('create/', views.SnsCreateView.as_view(), name='sns_create'),
    path('update/<int:pk>', views.SnsUpdateView.as_view(), name='sns_update'),
    path('delete/<int:pk>', views.SnsDeleteView.as_view(), name='sns_delete'),
    path('comment/', views.add_comment, name='sns_comment'),
    ]

templates/comment/comment.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS投稿・新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶SNS 新規・投稿作成
        <hr/>
        <form method="POST" action="{% url 'sns:sns_create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm">送信</button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/comment/create.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS投稿・新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶SNS 新規・投稿作成
        <hr/>
        <form method="POST" action="{% url 'sns:sns_create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
                {{ sns_comment_form.as_p }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm">送信</button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/comment/detail.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS詳細{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
            ▶Todo詳細表示
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>id</th>
                    <td>{{ sns.pk }}</td>
                </tr>
                <tr>
                    <th>タイトル</th>
                    <td>{{ sns.title }}</td>
                </tr>
                <tr>
                    <th>投稿内容</th>
                    <td>{{ sns.description }}</td>
                </tr>
                <tr>
                    <th>作成日</th>
                    <td> {{ sns.created_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
                <tr>
                    <th>更新日</th>
                    <td> {{ sns.updated_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
            </table><br/>

        <div class="card" style="width: 18rem;">
            <h6 class="card-title">【タイトル: {{ sns.title }}】{{ sns.updated_at|date:"Y-m-j" }}</h6>
            <div class="card-body">
                <p class="card-text">{{ sns.description }}</p>
                <a href="#" class="badge bg-secondary">Link先</a>
            </div>
            <img src="/media/{{ sns.post_image }}" class="card-img-top" alt="'post-image"/>
        </div>
        <div>
            <form action="" method="POST" name="sns_comment_form" id="sns_comment_form_id">
            {% csrf_token %}
            {{ sns_comment_form.non_field_errors }}
            <div class="form-group">
              {{ sns_comment_form.as_table }}
              <button type="submit" class="btn btn-primary" name="button_sns_comment_post"> 変更 </button>
            </div>
          </form>
        </div>
</div>
{% endblock %}

templates/comment/index.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS一覧{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        SNS・投稿・一覧 ▶[{{ me }}]<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-primary" href="{% url "sns:sns_create" %}">新規投稿</a>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <hr/>
        {% for sns in object_list %}
            <div class="card" style="width: 22rem;">
                <h6 class="card-title">
                    <img src="/static/bootstrap-icons/icons/person-plus.svg" alt="" width="16" height="16"/>
                    @{{ me }}<a href="{% url 'sns:sns_detail' sns.pk %}"> {{ sns.title }} </a>
                    {{ sns.updated_at|date:"Y-m-j" }}</h6>
                <!-- div class="card-body" -->
                <p class="card-text">{{ sns.description }}</p>
                <div class="float-sm-right">
                <div class="btn-group float-sm-right" role="group" aria-label="button-group1">
                    <div><a href="#" class="badge bg-secondary">Link先</a></div>&nbsp;
                    <div><a href="{% url 'sns:sns_update' sns.pk %}" class="badge bg-secondary">更新</a></div>&nbsp;
                    <div><a href="{% url 'sns:sns_delete' sns.pk %}" class="badge bg-secondary">削除</a></div>
                </div>
                </div>
                <!-- /div -->
                {% if sns.post_image != null %}
                    <img src="/media/{{ sns.post_image }}" class="card-img-top" alt="'post-image"/>
                {% endif %}
                <div class="btn-group" role="group" aria-label="button-group2">
                    <button type="button" class="btn btn-sm btn-success">
                        いいね <span class="badge bg-warning">200</span>
                    </button>
                    <button type="button" class="btn btn-sm btn-primary">
                        コメント <span class="badge bg-warning">4</span>
                    </button>
                </div>
                <div>　</div>
            </div>
        {% endfor %}
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>

    </div>
{% endblock %}