django_lesson/urls.py
#
from django.conf.urls import url
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import path, include
from django.contrib import admin
from django_lesson import settings


def home(request):
    if request.method == 'GET':
        msg = {'message': 'Hello there'}
        return render(request, 'index.html', msg)
    # loginしていなかったら、login → (/auth/login)へリダイレクトする


urlpatterns = [
                  path('home/', home, name="home"),
                  path('admin/', admin.site.urls),
                  path('todo/', include('todo.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('plot/', include('plot.urls')),
                  path('sns/', include('sns.urls')),
                  path('sns_comment/', include('sns_comment.urls')),
                  path('auth/', include('allauth.urls')),
                  path('', include('accounts.urls')),
                  url(r'^rest-auth/', include('rest_auth.urls')),
                  url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sns/urls.py
from django.urls import path

from sns import views

app_name = 'sns'

urlpatterns = [
    path('', views.SnsIndexView.as_view(), name='sns_index'),
    path('detail/<int:pk>', views.SnsDetailView.as_view(), name='sns_detail'),
    path('create/', views.SnsCreateView.as_view(), name='sns_create'),
    path('update/<int:pk>', views.SnsUpdateView.as_view(), name='sns_update'),
    path('delete/<int:pk>', views.SnsDeleteView.as_view(), name='sns_delete'),
    path('comment/', views.add_comment, name='sns_comment'),
    ]

sns_comment/urls.py
from django.urls import path

from sns_comment import views

app_name = 'sns_comment'

urlpatterns = [
    path('', views.SnsCommentIndexView.as_view(), name='sns_comment_index'),
    path('detail/<int:pk>', views.SnsCommentDetailView.as_view(), name='sns_comment_detail'),
    path('create/', views.SnsCommentCreateView.as_view(), name='sns_comment_create'),
    path('update/<int:pk>', views.SnsCommentUpdateView.as_view(), name='sns_comment_update'),
    path('delete/<int:pk>', views.SnsCommentDeleteView.as_view(), name='sns_comment_delete'),
    ]

sns/models.py
# マイグレーション
# $ python3 manage.py makemigrations
# $ python3 manage.py migrate
# from imagekit.models import ImageSpecField, ProcessedImageField
# from imagekit.processors import ResizeToFill
#

from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from sns_comment.models import SnsComment


class Sns(models.Model):  # sns_mention
    class Meta:
        managed = True
        db_table = 'sns'
        verbose_name_plural = 'sns'

    # user=me
    me = models.ForeignKey(CustomUser, verbose_name='自分・ユーザー', on_delete=models.CASCADE, related_name='sns_me')
    title = models.CharField(verbose_name='タイトル', blank=False, max_length=32)
    description = models.TextField(verbose_name='内容', null=False, blank=False, max_length=128)
    post_image = models.ImageField(
        upload_to='images/', verbose_name='投稿画像',
        validators=[FileExtensionValidator(['png', ])],
        blank=True, null=True)
    comments = models.ForeignKey(SnsComment, verbose_name='コメント', on_delete=models.PROTECT, default=1)
    like_count = models.IntegerField(verbose_name='いいね数', default=0, null=False)
    comment_count = models.IntegerField(verbose_name='コメント数', default=0, null=False)

    created_at = models.DateTimeField(default=timezone.now, verbose_name='登録日時')
    updated_at = models.DateTimeField(default=timezone.now, verbose_name='更新日時')

    def __str__(self):
        return self.title + '→' + self.me.username

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Sns, self).save(*args, **kwargs)


class Friend(models.Model):
    class Meta:
        managed = True
        db_table = 'friend'
        verbose_name = 'フレンド'

    # me user_id 私の
    # friend_id 友達
    me = models.ForeignKey(CustomUser, verbose_name='自分・ユーザー', on_delete=models.CASCADE, related_name='friend_me')
    my_friend = models.ForeignKey(CustomUser, verbose_name='フレンズ', on_delete=models.CASCADE)


class LikeOn(models.Model):
    class Meta:
        managed = True
        db_table = 'favorite'

    sns = models.ManyToManyField(Sns, verbose_name='メンション')
    like_up = models.BooleanField(default=False)

sns_comment/models.py
# SNS Comment

from django.db import models
from django.utils import timezone

from accounts.models import CustomUser


class SnsComment(models.Model):
    class Meta:
        managed = True
        db_table = 'sns_comment'

    # 投稿_id >> sns = sns mention_id - sns_comment
    # sns = models.ForeignKey(Sns, verbose_name='mention', on_delete=models.PROTECT)
    # mention(sns)へ投稿する投稿者ID　=login_user
    me = models.ForeignKey(CustomUser, verbose_name='コメント者', on_delete=models.PROTECT, default=1)
    comment = models.TextField(verbose_name='コメント', blank=False, max_length=128)
    created_at = models.DateTimeField(default=timezone.now, verbose_name='登録日時')
    updated_at = models.DateTimeField(default=timezone.now, verbose_name='更新日時')

    def __str__(self):
        return self.comment + '<< ' + self.me.pk

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        # me = login_user_id
        # self.me = self.request.user
        return super(SnsComment, self).save(*args, **kwargs)

sns/forms.py
# sns
from django import forms

from sns.models import Sns
from sns_comment.models import SnsComment


class SnsForm(forms.ModelForm):
    class Meta:
        model = Sns
        fields = ('title', 'description', 'post_image', 'me')

        title = forms.CharField(label='タイトル', max_length=32)
        description = forms.CharField(label='内容', max_length=128)  # models = TextField
        post_image = forms.ImageField(label='画像ファイル')
        widgets = {
            'post_image': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }
        title.widget.attrs.update({'class': 'form-control'})
        description.widget.attrs.update({'class': 'form-control'})

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 6:
            raise forms.ValidationError('6文字以上入力してください。')
        return title


# CommentFormset = forms.inlineformset_factory(
#     Sns, SnsComment, fields='__all__',
#     extra=1, max_num=1, can_delete=False
# )

sns/views.py
import logging

from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from extra_views import InlineFormSet, InlineFormSetFactory, CreateWithInlinesView

from sns.forms import SnsForm
from sns.models import Sns
from sns_comment.forms import SnsCommentForm
from sns_comment.models import SnsComment

logger = logging.getLogger(__name__)


def add_comment(request):
    form = SnsForm(request.POST or None)
    context = {'form': form}
    # post
    # if request.method == 'POST' and form.is_valid():
    #     # sns = form.save(commit=False)
    #     # comment_formset = CommentFormset(request.POST, files=request.FILES, instance=sns)
    #     comment_formset = CommentFormset(request.POST, instance=sns)
    #     if comment_formset.is_valid().is_valid():
    #         # sns.save()
    #         comment_formset.save()
    #         return redirect('sns:sns_index')
    #     else:
    #         context['comment_formset'] = comment_formset
    # # get
    # else:
    #     # 空のformsetをテンプレートへ渡す
    #     context['comment_formset'] = CommentFormset()

    return render(request, 'sns/comment.html', context)


# 投稿の下にコメントのフォオーム
class SnsCommentInlineFormSet(InlineFormSet):
    model = SnsComment
    fields = ('comment',)
    on_delete = False


class SnsCreateInlineFormSet(CreateWithInlinesView):
    model = Sns
    fields = ('title',)
    inlines = [SnsCommentInlineFormSet, ]                   # {% for form in inlines %}
    template_name = 'sns/sns_comment_formset.html'
    success_url = 'sns:sns_index'


class SnsIndexView(ListView):
    model = Sns
    template_name = 'sns/index.html'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['me'] = self.request.user
        return context

    def get_queryset(self):
        object_list = Sns.objects.order_by('pk').all()
        # object_list = Sns.objects.filter(user=self.request.user).order_by('-sns.pk').all()
        return object_list


class SnsDetailView(DetailView):
    model = Sns
    template_name = 'sns/detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['me'] = self.request.user
        self.request.session['sns_title'] = self.object.title
        self.request.session['sns_description'] = self.object.description
        return context


class SnsCreateView(CreateView):
    model = Sns
    form_class = SnsForm
    template_name = "sns/create.html"
    success_url = reverse_lazy('sns:sns_index')

    def form_valid(self, form):
        sns = form.save(commit=False)
        sns.user = self.request.user  # Login-userをセットする
        logger.info('--- sns create view ---2-')
        sns.me = self.request.user
        sns.save()
        messages.success(self.request, 'SNSを新規作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "SNSの新規作成に失敗しました。")
        return super().form_invalid(form)


class SnsCommentView(DetailView, generic.edit.ModelFormMixin):
    # model = Sns
    fields = ()
    form_sns = SnsForm
    form_comment = SnsCommentForm
    template_name = 'sns/sns_comment_formset.html'

    def post(self, request):
        post_data = request.POST or None
        post_form = self.form_sns(post_data, prefix='post')
        comment_form = self.form_comment(post_data, prefix='sns_comment')
        context = self.get_context_data(post_form=post_form, comment_form=comment_form)
        if post_form.is_valid():
            self.form_save(post_form)
        if comment_form.is_valid():
            self.form_save(comment_form)

        return self.render_to_response(context)

    def form_save(self, form):
        obj = form.save()
        messages.success(self.request, "{} saved successfully".format(obj))
        return obj

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        post_form = forms.SnsForm(**self.get_form_kwargs())
        comment_form = forms.SnsCommentForm(**self.get_form_kwargs())
        context.update({'post_form': post_form})
        context.update({'comment_form': comment_form})
        return self.render_to_response(context)

    def get_queryset(self):
        object_list = Sns.objects.order_by('pk').all()
        # object_list = Sns.objects.filter(user=self.request.user).order_by('-sns.pk').all()
        return object_list


class SnsUpdateView(UpdateView):
    model = Sns
    form_class = SnsForm
    template_name = "sns/update.html"
    success_url = reverse_lazy('sns:sns_index')

    def get_success_url(self):
        return reverse_lazy('sns:sns_detail', kwargs={'pk': self.kwargs['pk']})


class SnsDeleteView(DeleteView):
    model = Sns
    form_class = SnsForm
    template_name = "sns/delete.html"
    success_url = reverse_lazy('sns:sns_index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "SNSを削除しました。")
        return super().delete(request, *args, **kwargs)

templates/sns/comment.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS投稿・新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶SNS 新規・投稿作成<br/>
        {{ comment_formset }}
        <hr/>
        <form method="POST" action="#" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm">送信</button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/sns/detail.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS詳細{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo詳細表示<br/>
        me=: {{ me }}/{{ me.id }}<br/>
        sns=:{{ sns }}>/{{ sns.id }}/{{ sns.title }}<br/>
        comment:{{ sns.snscomment_set }}
        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>id</th>
                <td>{{ sns.pk }}</td>
            </tr>
            <tr>
                <th>タイトル</th>
                <td>{{ sns.title }}</td>
            </tr>
            <tr>
                <th>投稿内容</th>
                <td>{{ sns.description }}</td>
            </tr>
            <tr>
                <th>作成日</th>
                <td> {{ sns.created_at|date:"Y-m-j H:i:s" }}</td>
            </tr>
            <tr>
                <th>更新日</th>
                <td> {{ sns.updated_at|date:"Y-m-j H:i:s" }}</td>
            </tr>
        </table>
        <br/>

        <div class="card" style="width: 18rem;">
            <h6 class="card-title">【タイトル: {{ sns.title }}】{{ sns.updated_at|date:"Y-m-j" }}</h6>
            <div class="card-body">
                <p class="card-text">{{ sns.description }}</p>
                <a href="#" class="badge bg-secondary">Link先</a>
            </div>
            <img src="/media/{{ sns.post_image }}" class="card-img-top" alt="'post-image"/>
        </div>
        <div>
            <a role="button" class="btn  btn-sm btn-outline-primary"
               href="{% url 'sns_comment:sns_comment_create' %}"> コメントする </a>
        </div>
        <div> Form </div>
    </div>
{% endblock %}

templates/sns/sns_comment_formset.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS投稿・新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶SNS Mention-Comment
        <hr/>
        <form method="POST" action="{% url 'sns:sns_comment' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <table class="table table-bordered table-sm table-striped">
            {% for form in inlines %}
                {{ form.as_table }}
            {% endfor %}
            </table>
            <button type="submit" class="btn btn-primary btn-sm"> 投稿 </button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/sns/update.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS更新{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo 更新 {{ sns.pk }}
        <hr/>
        <form method="post" action="{% url 'sns:sns_update' todo.pk %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
             <table class="table table-bordered table-sm table-striped">
            {{ form.as_table }}
             </table>
            <input type="submit" class="btn btn-sm btn-primary" value="更新">
            <br/>
    </div>
{% endblock %}