django_lesson/urls.py
#
from django.conf.urls import url
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import path, include
from django.contrib import admin
from django_lesson import settings


def home(request):
    if request.method == 'GET':
        msg = {'message': 'Hello there'}
        return render(request, 'index.html', msg)
    # loginしていなかったら、login → (/auth/login)へリダイレクトする


urlpatterns = [
                  path('home/', home, name="home"),
                  path('admin/', admin.site.urls),
                  path('todo/', include('todo.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('plot/', include('plot.urls')),
                  path('sns/', include('sns.urls')),
                  path('sns_comment/', include('sns_comment.urls')),
                  path('auth/', include('allauth.urls')),
                  path('', include('accounts.urls')),
                  url(r'^rest-auth/', include('rest_auth.urls')),
                  url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

plot/urls.py
from django.urls import path

from plot import views

app_name = 'plot'
urlpatterns = [
    path('', views.PlotIndexView.as_view(), name='plot_index'),
    # path('show/', views.PlotShowView.as_view(), name='plot_show'),
    ]

sns/urls.py
from django.urls import path

from sns import views

app_name = 'sns'

urlpatterns = [
    path('', views.SnsIndexView.as_view(), name='sns_index'),
    path('detail/<int:pk>', views.SnsDetailView.as_view(), name='sns_detail'),
    path('create/', views.SnsCreateView.as_view(), name='sns_create'),
    path('update/<int:pk>', views.SnsUpdateView.as_view(), name='sns_update'),
    path('delete/<int:pk>', views.SnsDeleteView.as_view(), name='sns_delete'),
    path('comment/', views.add_comment, name='sns_comment'),
    ]

todo/urls.py
#
import debug_toolbar
from django.conf.urls import url
from django.urls import path, include

from todo import views

app_name = 'todo'
urlpatterns = [
    path('', views.TodoIndexView.as_view(), name='todo_index'),
    path('detail/<int:pk>', views.TodoDetailView.as_view(), name='todo_detail'),
    path('create/', views.TodoCreateView.as_view(), name='todo_create'),
    path('create_category/', views.TodoCreateView.as_view(), name='todo_create_category'),
    path('update/<int:pk>', views.TodoUpdateView.as_view(), name='todo_update'),
    path('delete/<int:pk>', views.TodoDeleteView.as_view(), name='todo_delete'),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

todo/models.py
#
from django.db import models
from django.db.models import *
from django.utils import timezone

from accounts.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name='カテゴリー名')

    class Meta:
        managed = True
        verbose_name_plural = 'Category'
        db_table = 'category'

    def __str__(self):
        return self.name


class Todo(models.Model):
    class Meta:
        managed = True
        db_table = 'todo'

    name = models.CharField(verbose_name='タイトル名', blank=False, max_length=32)  # null=DB, blank=Form,
    description = models.CharField(verbose_name='内容', null=False, blank=False, max_length=32)
    due_date = models.DateTimeField(verbose_name='期限', null=False, blank=False)
    created_at = models.DateTimeField(default=timezone.now, verbose_name='登録日時')
    updated_at = models.DateTimeField(default=timezone.now, verbose_name='更新日時')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, verbose_name='カテゴリー選択')
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT, default=1)

    def __str__(self):
        return self.name + ' ' + self.category.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        # todo.me = self.request.user
        return super(Todo, self).save(*args, **kwargs)

todo/forms.py
#
from django import forms

from todo.models import Todo, Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

    name = forms.CharField(label='名前', max_length=32)
    name.widget.attrs.update({'class': 'form-control'})

    def __str__(self):
        return self.category


class TodoForm(forms.ModelForm):
    # デフォルトでidが付与、id=Integer, primary_key, autoincrement
    class Meta:
        model = Todo
        fields = ('name', 'description', 'due_date', 'category')
        widgets = {
            'due_date': forms.SelectDateWidget(empty_label=('年', '月', '日'))
        }

        name = forms.CharField(label='タイトル', max_length=32)
        description = forms.CharField(label='内容', max_length=32)
        due_date = forms.DateTimeField(label='期限')

        name.widget.attrs.update({'class': 'form-control'})
        description.widget.attrs.update({'class': 'form-control'})
        due_date.widget.attrs.update({'class': 'form-control'})

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 6:
            raise forms.ValidationError('6文字以上入力してください。')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if len(description) < 1:
            raise forms.ValidationError('内容を入力してください。')
        return description

    # def clean_due_date(self):
    #     due_date = self.cleaned_data.get('description')
    #     if (not due_date.year) or (not due_date.month) or (not due_date.day):
    #         raise forms.ValidationError('年月日を入力してください。')
    #     return due_date

todo/views.py
# pip3 install django-debug-toolbar
# https://django-extra-views.readthedocs.io/en/latest/index.html
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView, TemplateView
from django.views.generic.edit import ModelFormMixin

from todo.forms import TodoForm, CategoryForm
from todo.models import Todo, Category

logger = logging.getLogger(__name__)


# @login_required()
class TodoIndexView(ListView):
    model = Todo
    template_name = 'todo/index.html'
    paginate_by = 3
    # success_url = reverse_lazy('todo:todo_index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['categories'] = Category.objects.order_by('pk').all()
        return context

    def get_queryset(self):
        object_list = Todo.objects.filter(user=self.request.user).order_by('todo.id').all()
        return object_list


class TodoDetailView(DetailView):
    model = Todo
    form_class = TodoForm
    template_name = 'todo/detail.html'


class TodoCreateView(LoginRequiredMixin, CreateView):
    model = Todo
    form_class = TodoForm
    template_name = "todo/create.html"
    success_url = reverse_lazy('todo:todo_index')

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.user = self.request.user  # Login-userをセットする
        print(self.request.user)
        todo.save()
        messages.success(self.request, 'Todoを新規作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Todoの新規作成に失敗しました。")
        return super().form_invalid(form)


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = "todo/update.html"
    success_url = reverse_lazy('todo:todo_index')

    def get_success_url(self):
        return reverse_lazy('todo:todo_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'Todoを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Todoの更新に失敗しました。")
        return super().form_invalid(form)


class TodoDeleteView(DeleteView):
    model = Todo
    form_class = TodoForm
    template_name = "todo/delete.html"
    success_url = reverse_lazy('todo:todo_index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Todoを削除しました。")
        return super().delete(request, *args, **kwargs)

templates/todo/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
          integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Django Lesson</a>
        <form class="d-flex">
            <div class="btn-group" role="group" aria-label="login-user">
                <button type="button" class="btn btn-sm btn-success">LoginUser</button>
                <button type="button" class="btn btn-sm btn-outline-success">
                    {% if user.is_authenticated %}
                        {{ user.get_username }}
                    {% else %}-
                    {% endif %}
                </button>
            </div>
            <input class="form-control mr-3" type="search" placeholder="検索ワードの入力" aria-label="検索">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div>　</div>
        <div class="col-lg-2 order-1">
            <div class="list-group">
                <ul class="list-group nav" id="menu-all" role="tablist">
                    <li class="list-group-item list-group-item-success">基本</li>
                </ul>
                {% block todo_menu %}
                    <a href="{% url 'todo:todo_index' %}" class="list-group-item list-group-item-action active">
                        <img src="/static/bootstrap-icons/icons/layout-text-window-reverse.svg" alt="" width="24"
                             height="24"/>
                        　Todo(1対1,多)
                    </a>
                {% endblock %}

                {% block sns_menu %}
                    <a href="{% url 'sns:sns_index' %}" class="list-group-item list-group-item-action">
                        <img src="{% static 'bootstrap-icons/icons/shop.svg' %}" alt="" width="24" height="24"/>
                        　SNS(多対多)</a>
                {% endblock %}

                <a href="{% url 'plot:plot_index' %}" class="list-group-item list-group-item-action">
                    <img src="{% static 'bootstrap-icons/icons/diagram-3.svg' %}" alt="" width="24" height="24"/>
                    　OpenCV 画像処理</a>
                <a href="#" class="list-group-item list-group-item-secondary">
                    <img src="{% static 'bootstrap-icons/icons/person-plus.svg' %}" alt="" width="24" height="24"/>
                    　Rest-API</a>
                <a href="#" class="list-group-item list-group-item-secondary">
                    <img src="{% static 'bootstrap-icons/icons/envelope.svg' %}" alt="" width="24" height="24"/>
                    　クローリング</a>

                <a role="button" class="btn  btn-sm btn-outline-primary" href="/accounts/login">ログイン</a>
                <a role="button" class="btn  btn-sm btn-outline-secondary" href="/accounts/logout">ログアウト</a>

            </div>

                <hr>
            <div>
                <ul class="list-group nav" id="menu-all" role="tablist">
                    <li class="list-group-item list-group-item-success">発展</li>
                    <li class="list-group-item list-group-item-secondary">可視化</li>
                    <li class="list-group-item list-group-item-secondary">回帰</li>
                    <li class="list-group-item list-group-item-secondary">分類</li>
                    <li class="list-group-item list-group-item-secondary">解析</li>
                    <li class="list-group-item list-group-item-secondary">NN</li>
                    <li class="list-group-item list-group-item-secondary">GA</li>
                </ul>
            </div>

        </div>
        {% block content %}
            <div class="col-lg-7 border order-2">
                センター・コンテンツ
            </div>
        {% endblock %}
        <div class="col-lg-3 order-3">
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">情報1</li>
                    <li class="list-group-item">情報2</li>
                    <li class="list-group-item">
                        <div class="card">
                            <div class="card-header">
                                ヘッダー Todo-Base-Template
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">タイトル</h5>
                                <p class="card-text">説明文</p>
                                <a href="#" class="btn btn-primary">リンク先ボタン</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div>　
</div>
<div class="border g-2">
    <div class="border">
        <div class="row justify-content-md-center">
            &copy2020 Happy IT Semi
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</body>
</html>

templates/todo/create.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todo新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo 新規作成
        <hr/>
        <form method="POST" action="{% url 'todo:todo_create' %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm">送信</button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/todo/delete.html
{% extends 'todo/base.html' %}
{% load static %}
{% block title %}Todo削除確認{% endblock %}
{% block content %}
   <div class="col-lg-7 border order-2">
        ▶Todo 削除・確認
        <hr/>
        <form method="post" action="{% url 'todo:todo_delete' todo.pk %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-sm table-striped">
                <tr><th>id</th><td>{{ object.pk }}</td></tr>
                <tr><th>Todo名</th><td>{{ object.title }}</td></tr>
                <tr><th>内容</th><td>{{ object.description }}</td></tr>
                <tr><th>期限</th><td>{{ object.due_date|date:"Y-m-j H:i:s" }}</td></tr>
                <tr><th>作成日時</th><td>{{ todo.created_at|date:"Y-m-j H:i:s" }}</td></tr>
                <tr><th>更新日時</th><td> {{ todo.updated_at|date:"Y-m-j H:i:s" }}</td></tr>
            </table>
            <button type="submit" class="btn btn-sm btn-primary">削除</button>
            <a role="button" class="btn  btn-sm btn-outline-primary" href="{% url 'todo:todo_index' %}">一覧</a>
        </form>
        <br/>
    </div>
{% endblock %}

templates/todo/detail.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todo詳細{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
            ▶Todo詳細表示
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>id</th>
                    <td>{{ todo.pk }}</td>
                </tr>
                <tr>
                    <th>Todo名</th>
                    <td>{{ todo.name }}</td>
                </tr>
                <tr>
                    <th>カテゴリー</th>
                    <td> {{  todo.category.name }}</td>
                </tr>
                <tr>
                    <th>内容</th>
                    <td>{{ todo.description }}</td>
                </tr>
                <tr>
                    <th>期日</th>
                    <td>{{ todo.due_date|date:"Y-m-j H:i:s" }}</td>
                </tr>
                <tr>
                    <th>作成日</th>
                    <td> {{ todo.created_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
                <tr>
                    <th>更新日</th>
                    <td> {{ todo.updated_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
            </table>
        </div>
{% endblock %}

templates/todo/index.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todoインデックス{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo一覧<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-primary" href="{% url "todo:todo_create" %}">新規作成</a>
        <hr/>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>id</th>
                <th>Todo名</th>
                <th>カテゴリー</th>
                <th>内容</th>
                <th>期日</th>
                <th>作成日<br/>
                    更新日
                </th>
                <th>更新</th>
                <th>削除</th>
            </tr>
            </thead>
            <tbody>
            {% for todo in object_list %}
                <tr>
                    <td>{{ todo.pk }}</td>
                    <td><a href="{% url 'todo:todo_detail' todo.pk %}"> {{ todo.name }} </a></td>
                    <td>{{ todo.category.name }}</td>
                    <td>{{ todo.description }}</td>
                    <td>{{ todo.due_date|date:"Y-m-j" }}</td>
                    <td> {{ todo.created_at|date:"Y-m-j" }}<br/>
                        {{ todo.updated_at|date:"Y-m-j" }}</td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_update' todo.pk %}">更新</a></td>
                    <td><a role="button" class="btn  btn-sm btn-outline-primary"
                           href="{% url 'todo:todo_delete' todo.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>
        ・他のモデルからテーブル情報を読み取る：→Categoryクラス(categoryテーブル）<br/>
        ・contextオブジェクトを利用したselectの作成例<br>
        <select id="category_id" name="category" class="form-select" aria-label="カテゴリー">
            <option selected>カテゴリーの選択</option>
            {% for cat in categories %}
                <option value="{{ cat.name }}">{{ cat }}</option>
            {% endfor %}
        </select>
        <div>
            <form method="POST" action="{% url 'todo:todo_create_category' %}">
                {% csrf_token %}
                {{ form_non_field_errors }}
                <table class="table table-bordered table-sm">
                    {{ form2.as_table }}
                </table>
            </form>
        </div>

    </div>
{% endblock %}

templates/todo/update.html
{% extends './base.html' %}
{% load static %}
{% block title %}Todo更新{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo 更新 {{ todo.pk }}
        <hr/>
        <form method="post" action="{% url 'todo:todo_update' todo.pk %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
             <table class="table table-bordered table-sm table-striped">
            {{ form.as_table }}
             </table>
            <input type="submit" class="btn btn-sm btn-primary" value="更新">
            <br/>
    </div>
{% endblock %}