django_lesson/urls.py
#
from django.conf.urls import url
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import path, include
from django.contrib import admin
from django_lesson import settings


def home(request):
    if request.method == 'GET':
        msg = {'message': 'Hello there'}
        return render(request, 'index.html', msg)
    # loginしていなかったら、login → (/auth/login)へリダイレクトする


urlpatterns = [
                  path('home/', home, name="home"),
                  path('admin/', admin.site.urls),
                  path('todo/', include('todo.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('plot/', include('plot.urls')),
                  path('sns/', include('sns.urls')),
                  path('sns_comment/', include('sns_comment.urls')),
                  path('auth/', include('allauth.urls')),
                  path('', include('accounts.urls')),
                  url(r'^rest-auth/', include('rest_auth.urls')),
                  url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

plot/urls.py
from django.urls import path

from plot import views

app_name = 'plot'
urlpatterns = [
    path('', views.PlotIndexView.as_view(), name='plot_index'),
    # path('show/', views.PlotShowView.as_view(), name='plot_show'),
    ]

sns/urls.py
from django.urls import path

from sns import views

app_name = 'sns'

urlpatterns = [
    path('', views.SnsIndexView.as_view(), name='sns_index'),
    path('detail/<int:pk>', views.SnsDetailView.as_view(), name='sns_detail'),
    path('create/', views.SnsCreateView.as_view(), name='sns_create'),
    path('update/<int:pk>', views.SnsUpdateView.as_view(), name='sns_update'),
    path('delete/<int:pk>', views.SnsDeleteView.as_view(), name='sns_delete'),
    path('comment/', views.add_comment, name='sns_comment'),
    ]

sns_comment/urls.py
from django.urls import path

from sns_comment import views

app_name = 'sns_comment'

urlpatterns = [
    path('', views.SnsCommentIndexView.as_view(), name='sns_comment_index'),
    path('detail/<int:pk>', views.SnsCommentDetailView.as_view(), name='sns_comment_detail'),
    path('create/', views.SnsCommentCreateView.as_view(), name='sns_comment_create'),
    path('update/<int:pk>', views.SnsCommentUpdateView.as_view(), name='sns_comment_update'),
    path('delete/<int:pk>', views.SnsCommentDeleteView.as_view(), name='sns_comment_delete'),
    ]

todo/urls.py
#
import debug_toolbar
from django.conf.urls import url
from django.urls import path, include

from todo import views

app_name = 'todo'
urlpatterns = [
    path('', views.TodoIndexView.as_view(), name='todo_index'),
    path('detail/<int:pk>', views.TodoDetailView.as_view(), name='todo_detail'),
    path('create/', views.TodoCreateView.as_view(), name='todo_create'),
    path('create_category/', views.TodoCreateView.as_view(), name='todo_create_category'),
    path('update/<int:pk>', views.TodoUpdateView.as_view(), name='todo_update'),
    path('delete/<int:pk>', views.TodoDeleteView.as_view(), name='todo_delete'),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

sns_comment/models.py
# SNS Comment

from django.db import models
from django.utils import timezone

from accounts.models import CustomUser


class SnsComment(models.Model):
    class Meta:
        managed = True
        db_table = 'sns_comment'

    # 投稿_id >> sns = sns mention_id - sns_comment
    # sns = models.ForeignKey(Sns, verbose_name='mention', on_delete=models.PROTECT)
    # mention(sns)へ投稿する投稿者ID　=login_user
    me = models.ForeignKey(CustomUser, verbose_name='コメント者', on_delete=models.PROTECT, default=1)
    comment = models.TextField(verbose_name='コメント', blank=False, max_length=128)
    created_at = models.DateTimeField(default=timezone.now, verbose_name='登録日時')
    updated_at = models.DateTimeField(default=timezone.now, verbose_name='更新日時')

    def __str__(self):
        return self.comment + '<< ' + self.me.pk

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        # me = login_user_id
        # self.me = self.request.user
        return super(SnsComment, self).save(*args, **kwargs)

sns_comment/forms.py
# sns
from django import forms
from sns_comment.models import SnsComment


class SnsCommentForm(forms.ModelForm):
    class Meta:
        model = SnsComment
        fields = ('me', 'comment')

        comment = forms.CharField(label='コメント', max_length=128)
        comment.widget.attrs.update({'class': 'form-control'})

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 6:
            raise forms.ValidationError('6文字以上入力してください。')
        return title

sns_comment/views.py
import logging

from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from sns_comment.forms import SnsCommentForm
from sns_comment.models import SnsComment

logger = logging.getLogger(__name__)


class SnsCommentIndexView(ListView):
    model = SnsComment
    template_name = 'sns_comment/index.html'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        #
        return context

    def get_queryset(self):
        object_list = SnsComment.objects.order_by('pk').all()
        # object_list = Sns.objects.filter(user=self.request.user).order_by('-sns.pk').all()
        return object_list


class SnsCommentDetailView(DetailView):
    model = SnsComment
    template_name = 'sns_comment/detail.html'


class SnsCommentCreateView(CreateView):
    model = SnsComment
    form_class = SnsCommentForm
    template_name = "sns_comment/create.html"
    success_url = reverse_lazy('sns_comment:sns_comment_index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['me'] = self.request.user

        # if 'key' in request.session
        context['sns_title'] = self.request.session['sns_title']  # get session data
        context['sns_description'] = self.request.session['sns_description']
        del self.request.session['sns_title']
        del self.request.session['sns_description']
        return context

    def form_valid(self, form):
        sns_comment = form.save(commit=False)
        sns_comment.user = self.request.user

        sns_comment.me = self.request.user
        sns_comment.save()
        messages.success(self.request, 'SNS_Commentを新規作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "SNSコメントの新規作成に失敗しました。")
        return super().form_invalid(form)


class SnsCommentUpdateView(UpdateView):
    model = SnsComment
    form_class = SnsCommentForm
    template_name = "sns_comment/update.html"
    success_url = reverse_lazy('sns_comment:sns_comment_index')

    def get_success_url(self):
        return reverse_lazy('sns_comment:sns_comment_detail', kwargs={'pk': self.kwargs['pk']})


class SnsCommentDeleteView(DeleteView):
    model = SnsComment
    form_class = SnsCommentForm
    template_name = "sns_comment/delete.html"
    success_url = reverse_lazy('sns_comment:sns_comment_index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "SNSコメントを削除しました。")
        return super().delete(request, *args, **kwargs)

templates/sns_comment/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
          integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Django Lesson</a>
        <form class="d-flex">
            <div class="btn-group" role="group" aria-label="login-user">
                <button type="button" class="btn btn-sm btn-success">LoginUser</button>
                <button type="button" class="btn btn-sm btn-outline-success">
                    {% if user.is_authenticated %}
                        {{ user.get_username }}
                    {% else %}-
                    {% endif %}
                </button>
            </div>
            <input class="form-control mr-3" type="search" placeholder="検索ワードの入力" aria-label="検索">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div>　</div>
        <div class="col-lg-2 order-1">
            <div class="list-group">
                <ul class="list-group nav" id="menu-all" role="tablist">
                    <li class="list-group-item list-group-item-success">基本</li>
                </ul>
                {% block todo_menu %}
                    <a href="{% url 'todo:todo_index' %}" class="list-group-item list-group-item-action">
                        <img src="/static/bootstrap-icons/icons/layout-text-window-reverse.svg" alt="" width="24"
                             height="24"/>
                        　Todo(１対1,多)
                    </a>
                {% endblock %}

                {% block sns_menu %}
                    <a href="{% url 'sns:sns_index' %}" class="list-group-item list-group-item-action active">
                        <img src="{% static 'bootstrap-icons/icons/shop.svg' %}" alt="" width="24" height="24"/>
                        　SNS(多対多)</a>
                {% endblock %}

                <a href="{% url 'plot:plot_index' %}" class="list-group-item list-group-item-action">
                    <img src="{% static 'bootstrap-icons/icons/diagram-3.svg' %}" alt="" width="24" height="24"/>
                    　OpenCV 画像処理</a>
                <a href="#" class="list-group-item list-group-item-secondary">
                    <img src="{% static 'bootstrap-icons/icons/person-plus.svg' %}" alt="" width="24" height="24"/>
                    　Rest-API</a>
                <a href="#" class="list-group-item list-group-item-secondary">
                    <img src="{% static 'bootstrap-icons/icons/envelope.svg' %}" alt="" width="24" height="24"/>
                    　クローリング</a>

                <a role="button" class="btn  btn-sm btn-outline-primary" href="/accounts/login">ログイン</a>
                <a role="button" class="btn  btn-sm btn-outline-secondary" href="/accounts/logout">ログアウト</a>

            </div>

                <hr>
            <div>
                <ul class="list-group nav" id="menu-all" role="tablist">
                    <li class="list-group-item list-group-item-success">発展</li>
                    <li class="list-group-item list-group-item-secondary">可視化</li>
                    <li class="list-group-item list-group-item-secondary">回帰</li>
                    <li class="list-group-item list-group-item-secondary">分類</li>
                    <li class="list-group-item list-group-item-secondary">解析</li>
                    <li class="list-group-item list-group-item-secondary">NN</li>
                    <li class="list-group-item list-group-item-secondary">GA</li>
                </ul>
            </div>

        </div>
        {% block content %}
            <div class="col-lg-7 border order-2">
                センター・コンテンツ
            </div>
        {% endblock %}
        <div class="col-lg-3 order-3">
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">情報1</li>
                    <li class="list-group-item">情報2</li>
                    <li class="list-group-item">
                        <div class="card">
                            <div class="card-header">
                                ヘッダー Todo-Base-Template
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">タイトル</h5>
                                <p class="card-text">説明文</p>
                                <a href="#" class="btn btn-primary">リンク先ボタン</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div>　
</div>
<div class="border g-2">
    <div class="border">
        <div class="row justify-content-md-center">
            &copy2020 Happy IT Semi
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</body>
</html>

templates/sns_comment/create.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS投稿・新規作成{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶SNS コメント作成<br/>
        {{ me }} / {{ sns_title }} / {{ sns_description }}
        <hr/>
        <form method="POST" action="{% url 'sns_comment:sns_comment_create' %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary btn-sm">送信</button>
        </form>
        <br/>
    </div>
{% endblock %}

templates/sns_comment/delete.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS削除確認{% endblock %}
{% block content %}
   <div class="col-lg-7 border order-2">
        ▶Todo 削除・確認
        <hr/>
        <form method="post" action="{% url 'sns:sns_delete' sns.pk %}">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-sm table-striped">
                <tr><th>id</th><td>{{ object.pk }}</td></tr>
                <tr><th>タイトル</th><td>{{ object.title }}</td></tr>
                <tr><th>投稿内容</th><td>{{ object.description }}</td></tr>
                <tr><th>作成日時</th><td>{{ todo.created_at|date:"Y-m-j H:i:s" }}</td></tr>
                <tr><th>更新日時</th><td> {{ todo.updated_at|date:"Y-m-j H:i:s" }}</td></tr>
            </table>
            <button type="submit" class="btn btn-sm btn-primary">削除</button>
            <a role="button" class="btn  btn-sm btn-outline-primary" href="{% url 'sns:sns_index' %}">一覧</a>
        </form>
        <br/>
    </div>
{% endblock %}

templates/sns_comment/detail.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS詳細{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
            ▶SNS 詳細表示 - コメント
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>id</th>
                    <td>{{ sns.pk }}</td>
                </tr>
                <tr>
                    <th>タイトル</th>
                    <td>{{ sns.title }}</td>
                </tr>
                <tr>
                    <th>投稿内容</th>
                    <td>{{ sns.description }}</td>
                </tr>
                <tr>
                    <th>作成日</th>
                    <td> {{ sns.created_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
                <tr>
                    <th>更新日</th>
                    <td> {{ sns.updated_at|date:"Y-m-j H:i:s" }}</td>
                </tr>
            </table><br/>

        <div class="card" style="width: 18rem;">
            <h6 class="card-title">【タイトル: {{ sns.title }}】{{ sns.updated_at|date:"Y-m-j" }}</h6>
            <div class="card-body">
                <p class="card-text">{{ sns.description }}</p>
                <a href="#" class="badge bg-secondary">Link先</a>
            </div>
            <img src="/media/{{ sns.post_image }}" class="card-img-top" alt="'post-image"/>
        </div>
        <div>
            <form action="" method="POST" name="sns_comment_form" id="sns_comment_form_id">
            {% csrf_token %}
            {{ sns_comment_form.non_field_errors }}
            <div class="form-group">
              {{ sns_comment_form.as_table }}
              <button type="submit" class="btn btn-primary" name="button_sns_comment_post"> 変更 </button>
            </div>
          </form>
        </div>
</div>
{% endblock %}

templates/sns_comment/index.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS一覧{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        SNS・コメント一覧 ▶[{{ me }}]<br/>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        {% endif %}
        <hr/>
        <a role="button" class="btn  btn-sm btn-outline-primary" href="{% url "sns_comment:sns_comment_create" %}">コメント投稿</a>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <hr/>
        {% for sns in object_list %}
            <div class="card" style="width: 22rem;">
                <h6 class="card-title">
                    <img src="/static/bootstrap-icons/icons/person-plus.svg" alt="" width="16" height="16"/>
                    @{{ me }}<a href="{% url 'sns_comment:detail' sns.pk %}"> {{ sns_comment.comment }} </a>
                    {{ sns_comment.updated_at|date:"Y-m-j" }}</h6>
                <!-- div class="card-body" -->
                <p class="card-text">{{ sns.description }}</p>
                <div class="float-sm-right">
                <div class="btn-group float-sm-right" role="group" aria-label="button-group1">
                    <div><a href="#" class="badge bg-secondary">Link先</a></div>&nbsp;
                    <div><a href="{% url 'sns:sns_update' sns_comment.pk %}" class="badge bg-secondary">更新</a></div>&nbsp;
                    <div><a href="{% url 'sns:sns_delete' sns_comment.pk %}" class="badge bg-secondary">削除</a></div>
                </div>
                </div>
                <!-- /div -->
                {% if sns.post_image != null %}
                    <img src="/media/{{ sns.post_image }}" class="card-img-top" alt="'post-image"/>
                {% endif %}
                <div class="btn-group" role="group" aria-label="button-group2">
                    <button type="button" class="btn btn-sm btn-success">
                        いいね <span class="badge bg-warning">200</span>
                    </button>
                    <button type="button" class="btn btn-sm btn-info">
                        コメント <span class="badge bg-warning">4</span>
                    </button>
                </div>
                <div>　</div>
            </div>
        {% endfor %}
        <br/>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <br/>

    </div>
{% endblock %}

templates/sns_comment/update.html
{% extends './base.html' %}
{% load static %}
{% block title %}SNS更新{% endblock %}
{% block content %}
    <div class="col-lg-7 border order-2">
        ▶Todo 更新 {{ sns.pk }}
        <hr/>
        <form method="post" action="{% url 'sns:sns_update' sns.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_non_field_errors }}
            <table class="table table-bordered table-sm table-striped">
                {{ form.as_table }}
            </table>
            <input type="submit" class="btn btn-sm btn-primary" value="更新"/>
            <br/>
        </form>
    </div>
{% endblock %}